services:
  next:
    image: ghcr.io/kemrode/learncicd:latest
    restart: always
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-production.rule=Host(`ec2-54-89-142-103.compute-1.amazonaws.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.next-production.entrypoints=web"
      # - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/next"
      # - "traefik.http.routers.next-production.middlewares=test-stripprefix"

  db:
    image: mariadb:10.6
    environment:
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: cube
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./docker/db/data:/var/lib/mysql

  
  adminer:
    image: adminer
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-adminer.rule=Host(`ec2-54-89-142-103.compute-1.amazonaws.com`) && PathPrefix(`/adminer`)"
      - "traefik.http.routers.next-adminer.entrypoints=web"

  
networks:
  reverse-proxy:
    name: reverse-proxy
    external: true