name: buildlearncicd
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
             node_modules
             /home/runner/.cache/Cypress
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - name: Install and run build
          run: |
            cd learncicdapp
            npm install
            npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
              node_modules
              /home/runner/.cache/Cypress
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - name: Test e2e
          run: |
           cd learncicdapp
           npm run e2e:headless
        - name: Archive cypress video results
          uses: actions/upload-artifact@v3
          with:
            name: cypress-video-report
            path: /home/runner/work/learnCICD/learnCICD/learncicdapp/cypress/videos/app.cy.ts.mp4 