name: buildlearncicd
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
             learncicdapp/node_modules
             /home/runner/.cache/Cypress
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - run: |
            cd learncicdapp
            npm install
            npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
              learncicdapp/node_modules
              /home/runner/.cache/Cypress
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - run: |
            cd learncicdapp
            npm run e2e:headless
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: cypress-video-report
            path: learncicdapp/cypress/videos/
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST}} "cd learncicdapp ls"